# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RASATGK2_SatelliteImage_Loader
                                 A QGIS plugin
 RASAT ve Göktürk-2 uydu görüntülerini QGIS yükleme programı
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-05
        copyright            : (C) 2020 by TÜBİTAK UZAY
        email                : mustafa.teke@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RASATGK2_SatelliteImage_Loader class from file RASATGK2_SatelliteImage_Loader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TrSatImageLoader import RASATGK2_SatelliteImage_Loader
    return RASATGK2_SatelliteImage_Loader(iface)
